### ISSUE TITLE
Add better error handling to `opm`

### ISSUE THREAD

**Issue by arewm** [operator-framework/operator-registry#1039]
We were trying to add a bundle to an index and were getting an error message 
```
unrecognized type: string
```
using both the `add` and `render` commands. There should should be better error handling to make debugging of these issues easier.

This has been encountered multiple times. We traced down the suspected offending lines to when the `spec.version` was a string as well as when `metadata.annotations.*` were not strings, for example,

```
metadata:
  annotations:
    certified: true
```

Related issue in operator-sdk: https://github.com/operator-framework/operator-sdk/issues/6168

**Comment by grokspawn** [comment]
Closing this one as completed.  Please re-open if you continue to encounter this.
