### ISSUE TITLE
BUG: JSON output that eventually ends up in FBC indexes (catalog.json) is invalid

### ISSUE THREAD

**Issue by bentito** [operator-framework/operator-registry#1053]
Most (all?) of the `catalog.json` files for individual operators in the Red Hat OpenShift 4.11 or 4.12+ indexes are auto-generated by `opm` migrating SQLite indexes. While the filenames end in `.json`, the contents are not valid JSON. They can be fixed by, for instance, adding commas between all elements and wrapping in an array. While this quick fix is perhaps not logical, it does allow standard JSON marshalling code to bring in the data.

**Comment by cdjohnson** [comment]
@bentito This data is in JSON Stream format.  A stream of JSON objects.  This was done on purpose to support larger catalogs, I believe:
https://en.wikipedia.org/wiki/JSON_streaming

I've successfully used `jq` and other libraries to parse the catalog properly.  Here's an example of one such command that will split the `catalog.json` file into one file per schema-name (for those objects that have names).

`cat catalog.json | jq -sr '.[] | @sh "cat >\(.schema)-\(.name).json <<\\END",.,"END"' | sh`

**Comment by bentito** [comment]
okay, but this defeats standard marshallers everywhere (Java, Javascript,
Python, etc) and adds a requirement that jq, or something like it, be
around for any pipeline that wants to deal with these.
