### ISSUE TITLE
appregistry always report warning when download package

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-registry#132]
I created three CSV for one application and pushed to quay.io, after the operatorsource was created, the appregistry always report warning as follows, but I can still create the subscription successfully and 0.0.3 CSV and operators can be created successfully.

```
time="2019-12-05T09:04:35Z" level=info msg=directory dir=downloaded file=0.0.1 load=package
time="2019-12-05T09:04:35Z" level=info msg=directory dir=downloaded file=0.0.2 load=package
time="2019-12-05T09:04:35Z" level=info msg=directory dir=downloaded file=0.0.3 load=package
time="2019-12-05T09:04:35Z" level=info msg="serving registry" port=50051 type=appregistry
time="2019-12-05T09:04:35Z" level=warning msg="strict mode disabled" error="error loading manifests from appregistry: error loading operator manifests: error loading package into db: memcached-operator.v0.0.3 specifies replacement that couldn't be found" port=50051 type=appregistry
```
The attachment are my csv bundles.
[memcache.tar.gz](https://github.com/operator-framework/operator-registry/files/3925982/memcache.tar.gz)

**Comment by gyliu513** [comment]
FYI @clyang82

**Comment by njhale** [comment]
@gyliu513 Thanks for reaching out!

This is a warning indicating an issue with the update graph for the package. Looking at the manifests you've given, it seems that `memcached-operator.v0.0.1` specifies `memcached-operator.v0.0.0` as its replacement, which is missing from your bundles -- operator-registry notices it can't build the entire graph your existing CSVs define and correctly gives you a warning message. 

The message content is a little confusing though. I had though we had changed it in newer versions of the registry. Which version are you currently using?

**Comment by gyliu513** [comment]
Ah, I should remove the `replaces` for 0.0.1 as it is the first version. Thanks @njhale
