### ISSUE TITLE
Release v1.43.1 failed

### ISSUE THREAD

**Issue by suzuki-shunsuke** [operator-framework/operator-registry#1325]
No pre-built binary is released.

https://github.com/operator-framework/operator-registry/releases/tag/v1.43.1

<img width="284" alt="image" src="https://github.com/operator-framework/operator-registry/assets/13323303/8189e05c-7469-481a-bdb3-2e248c6ca9c7">

The release workflow run failed.

https://github.com/operator-framework/operator-registry/actions/runs/9224724486/job/25380995497#step:6:7

```
Run gh release create "v1.43.1" --generate-notes ./assets/*
a release with the same tag name already exists: v1.43.1
Error: Process completed with exit code 1.
```

https://github.com/operator-framework/operator-registry/blob/58f1d01329371b79b56ddfc9f12974e447e3a70c/.github/workflows/goreleaser.yaml#L47

**Comment by suzuki-shunsuke** [comment]
`gh release create` failed because the GitHub Release already existed.

Before running `gh release create`, GoReleaser was run.
I think GoReleaser created a GitHub Release so `gh release create` failed.

https://github.com/operator-framework/operator-registry/blob/58f1d01329371b79b56ddfc9f12974e447e3a70c/.github/workflows/goreleaser.yaml#L64
https://github.com/operator-framework/operator-registry/blob/58f1d01329371b79b56ddfc9f12974e447e3a70c/.github/workflows/goreleaser.yaml#L88
https://github.com/operator-framework/operator-registry/blob/58f1d01329371b79b56ddfc9f12974e447e3a70c/.github/workflows/goreleaser.yaml#L143

We can see the log of GoReleaser.

https://github.com/operator-framework/operator-registry/actions/runs/9224724486/job/25380594180

**Comment by suzuki-shunsuke** [comment]
Hmm. But if GoReleaser created a release uploaded assets, I'm not sure why no asset is released at v1.43.1.

**Comment by suzuki-shunsuke** [comment]
I found a log that the tag v1.43.1 was deleted at 2024-05-24 13:24 UTC.

<img width="466" alt="image" src="https://github.com/operator-framework/operator-registry/assets/13323303/25a7a77f-417c-4e25-921c-ef3e4071ba73">

**Comment by perdasilva** [comment]
Should be fixed now - sorry about that!

![Screenshot_20240528-135942.png](https://github.com/operator-framework/operator-registry/assets/785683/66a1d229-391e-45e3-ac17-74cb8a0bfe8a)

**Comment by suzuki-shunsuke** [comment]
Thank you for resolving this issue!
