### ISSUE TITLE
appregistry interprets whitespace followed by directives end mark differently than operator-courier

### ISSUE THREAD

**Issue by tmckayus** [operator-framework/operator-registry#133]
Consider a yaml file that begins like this (whitespace followed a directives end mark:
"

(dash dash dash ---)
"

(TL;DR although this is an edge case ,it really happened to a real company who was stymied  trying to run an operator on OpenShift :) ) 

The YAML spec is not quite clear on how this should be interpreted. In the Python3 standard yaml library, this will be interpreted as a single document. However, in k8s.io/apimachinery/pkg/util/yaml/decoder.go this will be treated as an empty document followed by a second document beginning at the directives end mark (---).

This leads to a scenario where a bundle can be validated by operator-courier and successfully upload but will fail when downloaded by the appregistry because the empty document will occlude the second document, resulting in a missing CRD in the bundle.

This in turn leads to a ClusterServiceVersion stuck in pending, with no clear error to the end user unless they are knowledgeable enough to look at pod logs in the openshift-marketplace and figure out what went wrong.

The solution is to reconcile the handling of the initial whitespace by operator-courier and appregistry. Either make operator-courier flag this as an error, even though standard Python3 treats it unambiguously, or make the appregistry handle the empty document without failing the bundle.

**Comment by ecordell** [comment]
I think that this is no longer an issue, since appregistry is no longer used, and validations are now implemented in a shared golang library (no language incompatibility issues)

Please re-open if you think there's still something we should look at.
