### ISSUE TITLE
When registry-server is running online, how do I add and delete bundles online

### ISSUE THREAD

**Issue by sky-big** [operator-framework/operator-registry#174]
Whether the registry-server service has an gRPC interface adds and deletes bundles directly？

**Comment by sky-big** [comment]
Can I only log in to the container corresponding to the registry-server service and use the OPM tool to add?

**Comment by ecordell** [comment]
OPM is used to modify the contents of the catalog image, and the server serves a readonly copy of that data.

It's unlikely we'll add grpc APIs to mutate the content, but we will likely pursue some options that allow modifying the content at cluster runtime (it would still require a pod restart).
