### ISSUE TITLE
License issue with bou.ke/monkey package

### ISSUE THREAD

**Issue by adrian555** [operator-framework/operator-registry#190]
Refer to link https://github.com/bouk/monkey/blob/master/LICENSE.md for the license text for bou.ke/monkey package.

Tracking down the dependents on this package are `github.com/otiai10/copy@v1.0.1` and `github.com/otiai10/mint@v1.2.4`.

The owner of that `otiai10/copy` already updated the package to remove that dependency https://github.com/otiai10/copy/issues/12.

Need to update `go.mod` to pick up the correct versions to avoid the license problem.

**Comment by ankitathomas** [comment]
Dependency removed as of https://github.com/operator-framework/operator-registry/pull/193
