### ISSUE TITLE
Binaries or containers are not available for different architectures

### ISSUE THREAD

**Issue by kaczyns** [operator-framework/operator-registry#208]
It would be convenient if either:
1) The releases had binaries for s390x and ppc64le (linux platform only)
2) There were architecture-specific container images for s390x and ppc64le.  For example, if `quay.io/operator-framework/upstream-registry-builder` had tags for those two architectures.

Currently in order to produce a registry that I can use on another architecture, I have to compile operator-registry on that platform and then use the resulting executable to produce a registry / container.  This is time-consuming and error-prone on a Travis build.  On amd64 I can just use `upstream-registry-builder` to produce the registry, which is much easier and consistently works.

**Comment by plainchanter** [comment]
upstream-registry-builder can be build successfully on s390x if

`GRPC_HEALTH_PROBE_VERSION=v0.2.1`

is changed to

`GRPC_HEALTH_PROBE_VERSION=v0.3.2`

in upstream-build.Dockerfile.

**Comment by Jamstah** [comment]
We are about to start working on releasing an operator that needs s390x support as well.

**Comment by plainchanter** [comment]
Question for the maintainers: what would be involved in adding new platform support to the public builds?

**Comment by hassenius** [comment]
We are in the same situation where we have operators built for ppc64le and s390x, but we won't be able to run these on homogeneous clusters, as the catalog source cannot run on these currently.

**Comment by hassenius** [comment]
To summarize latest findings for others finding their way here, those with Red Hat subscription can pick up a multi-arch build from: https://catalog.redhat.com/software/containers/openshift4/ose-operator-registry/5cddd0bed70cc57c44b2e1f3?container-tabs=overview&gti-tabs=registry-tokens

**Comment by Jamstah** [comment]
Latest on this is that there is a broken unit test on s390x (the build system now attempts a build on that platform), which needs fixing. I'll look if I get time, but if anyone has a more urgent need, they should take a look.

**Comment by tdaleibm** [comment]
I see in @hassenius link a multiarch image "Operator Registry", but I cannot find a multiarch "upstream-image-builder" image in catalog.redhat.com. Does this exist?

**Comment by ecordell** [comment]
Because we lost free-tier s390x runners for upstream, those releases are no longer maintained.

The downstream images in `registry.redhat.io` do contain images and binaries for s390x and z.

> I cannot find a multiarch "upstream-image-builder" image in catalog.redhat.com. Does this exist?

There's no explicit image called this, but the `operator-registry` image contains all of the relevant binaries.

In the near future, the `opm` binary will be plucked and published alongside `oc` to avoid the need to pull it from the registry.

Since we can no longer support those arches upstream, please direct any other questions about them to the redhat bugzilla: bugzilla.redhat.com
