### ISSUE TITLE
openshift/oc k8s bump to 1.18 requires bump in operator-registry as well

### ISSUE THREAD

**Issue by ingvagabund** [operator-framework/operator-registry#223]
Workloads team is in the middle of rebasing oc to kubernetes 1.18. Oc command imports `github.com/operator-framework/operator-registry/pkg/appregistry` package which imports client-go. Client-go in 1.18 changed signature of Get, Update, Delete and other methods to have context.Context as their first parameter. This, the following change in the operator-registry code is required by oc:
```
vendor/github.com/operator-framework/operator-registry/pkg/appregistry/downloader.go 
index 18142d2..191406c 100644
@@ -1,6 +1,7 @@
 package appregistry
 import (
+	"context"
 	"errors"
 	"fmt"
@@ -251,7 +252,7 @@ func (s *secretRegistryOptionsGetter) GetRegistryOptions(source *Source) (*apprc
 	token := ""
 	if source.IsSecretSpecified() {
-		secret, err := s.kubeClient.CoreV1().Secrets(source.Secret.Namespace).Get(source.Secret.Name, metav1.GetOptions{})
+		secret, err := s.kubeClient.CoreV1().Secrets(source.Secret.Namespace).Get(context.TODO(), source.Secret.Name, metav1.GetOptions{})
 		if err != nil {
 			return nil, err
 		}
```
Which requires to also bump k8s dependencies in operator-registry to 1.18.

Filling the issue to track the progress of its resolution atm. We will carry a patch with the change meantime.

**Comment by estroz** [comment]
This was done in #246.

**Comment by ingvagabund** [comment]
@estroz thanks!!!
/close
