### ISSUE TITLE
opm 1.7.0: All channels deleted except for latest with opm registry add

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-registry#258]
When attempting to add additional channels, any previous channels are deleted.  Only the latest channel is preserved.

I believe this is a regression introduced in PR #236 as a result of issue #205 

1. Add a bundle to to the BETA channel:
```
operator-sdk bundle create quay.io/cdjohnson/brokenoperator:v1.0.0 --directory 1.0.0 --package test-operator --channels BETA --default-channel BETA
docker push quay.io/cdjohnson/brokenoperator:v1.0.0
opm registry add -b quay.io/cdjohnson/brokenoperator:v1.0.0 -c docker

sqlite3 bundles.db "select * from channel;"
BETA|test-operator|testoperator.v1.0.0

sqlite3 bundles.db "select * from channel_entry;"
1|BETA|test-operator|testoperator.v1.0.0||0

sqlite3 bundles.db "select name from operatorbundle;"
testoperator.v1.0.0
```

2. Add a second bundle to the STABLE channel where `olm.skipRange: <1.0.1`
```
operator-sdk bundle create quay.io/cdjohnson/brokenoperator:v1.0.1 --directory 1.0.1 --package test-operator --channels STABLE --default-channel STABLE
docker push quay.io/cdjohnson/brokenoperator:v1.0.1
opm registry add -b quay.io/cdjohnson/brokenoperator:v1.0.1 -c docker


sqlite3 bundles.db "select * from channel;"
STABLE|test-operator|testoperator.v1.0.1

sqlite3 bundles.db "select * from channel_entry;"
1|STABLE|test-operator|testoperator.v1.0.1||0

sqlite3 bundles.db "select name from operatorbundle;"
testoperator.v1.0.0
testoperator.v1.0.1
```

**Result:**  The BETA channel has been removed from both the `channel` and `channel_entry` table.

This SHOULD result in two separate channels and channel_entries.

[bundles.zip](https://github.com/operator-framework/operator-registry/files/4441177/bundles.zip)

**Comment by ecordell** [comment]
Thanks for reporting this regression @cdjohnson - just cut 1.8.0 which should fix this issue.

**Comment by narasimha-ntnx** [comment]
Hi, I am still facing this issue. I am using opm 1.23.
