### ISSUE TITLE
How to detect if a bundle exists

### ISSUE THREAD

**Issue by jdockter** [operator-framework/operator-registry#286]
Currently if I try to build an index with bundles that already exist in my --from-index I get the following error: `Error adding package error loading bundle into db: UNIQUE constraint failed: operatorbundle.name, operatorbundle.version, operatorbundle.bundlepath`

1) Is that error expected or am I potentially do something wrong?
2) If it is expected, how do I properly detect if a bundle exists so I know what bundles I can to an existing catalog index image?

I'm not seeing anything in the api.Registry where I can just send in the operator bundle path to see if it exists, ie 

`grpcurl -plaintext -d '{"bundlepath": "quay.io/jondockter/memcached-operator-bundle@sha256:4d87aea66488957a0211c70d8e79533977d11122e13f1638a63e092a25f4592f"}' localhost:50051 api.Registry.GetBundle`

Any insight or guidance on this would be appreciated, thanks.

**Comment by jdockter** [comment]
@ecordell any thoughts on this?

**Comment by kevinrizza** [comment]
@jdockter That is expected, attempting to add a bundle that already exists will necessarily result in an error. Right now, we don't have a very nice way of displaying what bundle images exist just by inspecting the index image. There is some discussion here about what it would look like:

https://github.com/operator-framework/enhancements/blob/master/enhancements/implicit-catalog-versioning.md#tooling

But it has not yet been fully implemented

**Comment by jdockter** [comment]
@kevinrizza any idea of when a `opm index inspect packages` and `opm index inspect package etcd` type of function will be available?

**Comment by kevinrizza** [comment]
@jdockter I was actually having a conversation with some of the maintainers about that yesterday. At the moment, we have a freeze on the master branch. I'm hopeful that this is one of the first things that will merge once we open back up for contributions in the next few weeks.

**Comment by jdockter** [comment]
@kevinrizza thanks, will check back in a couple of weeks.

**Comment by jdockter** [comment]
@kevinrizza any news on the inspect capability being implemented?

**Comment by mvalahtv** [comment]
I would be also interested

**Comment by jdockter** [comment]
@kevinrizza this still an enhancement that is in the works?  

Currently I have to run a catalog locally and hit the registry server API using ListBundles to pull out the existing bundles in the index.

`grpcurl -plaintext localhost:50051 api.Registry/ListBundles | jq '.bundlePath'`

**Comment by ecordell** [comment]
https://github.com/operator-framework/enhancements/pull/26

This enhancement should address this need - it should be easy to grep through this data to find an existing bundle.
