### ISSUE TITLE
Container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by bfabec** [operator-framework/operator-registry#291]
We just have tested with the latest opm (1.11.1) on OCP 4.4-RC7 and we are seeing something new where the catalogsource is not starting due to the following error:
`Error: container has runAsNonRoot and image will run as root`

You can recreate with the following index: quay.io/bfabec/noi-operator-index:scao01"
The index works fine on OCP 4.3ga.  Problem occurs with cluster or namespace scoped. 

```
root@ldap1:~/noioper# oc get pods -n openshift-marketplace
NAME                                    READY     STATUS                       RESTARTS   AGE
certified-operators-67cd5c7744-kzkdc    1/1       Running                      0          4h
community-operators-549c9c4c98-pqwjb    1/1       Running                      0          3h
marketplace-operator-5cc65c6b69-m7dpk   1/1       Running                      0          9d
noi-2zvgv                               0/1       CreateContainerConfigError   0          12m
opencloud-operators-868f54db89-bv28j    1/1       Running                      0          3h
redhat-marketplace-844b5db758-ptkbl     1/1       Running                      0          4h
redhat-operators-75bc7d947b-nhkbw       1/1       Running                      0   
```

```
oc describe pod noi-2zvgv -n openshift-marketplace
Name:               noi-2zvgv
Namespace:          openshift-marketplace
Priority:           0
PriorityClassName:  <none>
Node:               ip-10-0-133-169.ec2.internal/10.0.133.169
Start Time:         Mon, 20 Apr 2020 09:34:58 -0700
Labels:             olm.catalogSource=noi
Annotations:        k8s.v1.cni.cncf.io/networks-status=[{
    "name": "openshift-sdn",
    "interface": "eth0",
    "ips": [
        "10.129.2.107"
    ],
    "dns": {},
    "default-route": [
        "10.129.2.1"
    ]
...
         openshift.io/scc=nginx-ingress-scc
         seccomp.security.alpha.kubernetes.io/pod=docker/default
Status:  Pending
IP:      10.129.2.107
Containers:
  registry-server:
    Container ID:
    Image:          quay.io/bfabec/noi-operator-index:scao01
    Image ID:
    Port:           50051/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        10m
      memory:     50Mi
    Liveness:     exec [grpc_health_probe -addr=localhost:50051] delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:    exec [grpc_health_probe -addr=localhost:50051] delay=5s timeout=5s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-h2jnw (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-h2jnw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-h2jnw
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:
Events:
  Type     Reason     Age                 From                                   Message
  ----     ------     ----                ----                                   -------
  Normal   Scheduled  <unknown>           default-scheduler                      Successfully assigned openshift-marketplace/noi-2zvgv to ip-10-0-133-169.ec2.internal
  Normal   Pulling    12m                 kubelet, ip-10-0-133-169.ec2.internal  Pulling image "quay.io/bfabec/noi-operator-index:scao01"
  Normal   Pulled     12m                 kubelet, ip-10-0-133-169.ec2.internal  Successfully pulled image "quay.io/bfabec/noi-operator-index:scao01"
  Warning  Failed     10m (x12 over 12m)  kubelet, ip-10-0-133-169.ec2.internal  Error: container has runAsNonRoot and image will run as root
  Normal   Pulled     2m (x45 over 12m)   kubelet, ip-10-0-133-169.ec2.internal  Container image "quay.io/bfabec/noi-operator-index:scao01" already present on machine
root@ldap1:~/noioper#
```

**Comment by bfabec** [comment]
I believe it is related to https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36965.  Closing

**Comment by gajananan** [comment]
@bfabec 
Hi, I have been following the doc as here: https://github.com/operator-framework/operator-registry/blob/master/docs/design/opm-tooling.md#index

When creating CatalogSource,   catalogsource pod is not starting due to the following error:
`Error: container has runAsNonRoot and image will run as root`

is this issue already fixed ? Thank you.

My env:
  OpenShift 4.5

**Comment by bfabec** [comment]
@gajananan - I haven't seen this issue in a long time, but I'm using opm 1.12.2 with ocp 4.5/4.6.

**Comment by gajananan** [comment]
@bfabec 
Thank you.

I am using opm version v1.15.1 (latest)

To build index image
I tried to use the format https://github.com/operator-framework/operator-registry/blob/ef1f1ec54b72a701269df0bd7f5b7f0c4805de05/opm-example.Dockerfile

However, when I create a catalog resource referring to above index image, I run into 
`Error: container has runAsNonRoot and image will run as root`

Do you know how I could correctly change the user to nonroot in here: 
`https://github.com/operator-framework/operator-registry/blob/ef1f1ec54b72a701269df0bd7f5b7f0c4805de05/opm-example.Dockerfile`

When I changed user to 1001,  I get the error
`opm Error: no such table: package`

**Comment by bfabec** [comment]
@gajananan - if you are seeing this with the latest version then I would recommend opening a new issue as I'm not a contributor/developer of the operator-framework.

**Comment by gajananan** [comment]
@bfabec Thank you.
I found a way to fix it.

The following does not use non-root user, so the above issue occurs
`https://github.com/operator-framework/operator-registry/blob/ef1f1ec54b72a701269df0bd7f5b7f0c4805de05/opm-example.Dockerfile`  

When I build the index image,  the container image should be built with non-root user.  Then, catalog resource (Pod) can successfully be created.

doc: `https://github.com/operator-framework/operator-registry/blob/master/docs/design/opm-tooling.md#index`
