### ISSUE TITLE
In the validate ignore the files which are not used by it

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-registry#294]
## Scenario:

In some projects maintainers as been added in the bundle dir files which are not relevant to it. Then, the validation will fail in this scenario. 

**Example**

1- Just added in the manifest dir an extra yaml file

2- then, called the validate via operator-sdk 

```
$ operator-sdk bundle validate ./deploy/olm-catalog/memcached-operator/
FATA[0000] Bundle content validation failed: Bundle validation errors: Deployment is not supported type for registryV1 bundle: /Users/camilamacedo/go/src/github.com/operator-framework/operator-sdk-samples/go/memcached-operator/deploy/olm-catalog/memcached-operator/manifests/operator.yaml bundle-dir=/Users/camilamacedo/go/src/github.com/operator-framework/operator-sdk-samples/go/memcached-operator/deploy/olm-catalog/memcached-operator
```

## Possible solution:

Just check the valid files/types for the bundle ( CRD, CSV, annotations.yaml ) and ignore the others.

**Comment by camilamacedo86** [comment]
c/c @gallettilance

**Comment by gallettilance** [comment]
Just got confirmation that we don't need to do this. We should keep the above failure as expected behavior because these files should not be part of the bundle

**Comment by camilamacedo86** [comment]
Hi @gallettilance,  

It is great to hear. I think that the best would not allow as well and I was working to check it with its maintainers. Closing it.
