### ISSUE TITLE
Question: Different types

### ISSUE THREAD

**Issue by hassenius** [operator-framework/operator-registry#313]
Hi, 

I'm trying to understand the different ways of using the operator-registry (version 1.6 together with a bunch of operators built with operator-sdk 0.17)
There are some examples in this repo of different approaches, including configmap-registry, appr-registry, upstream-bundler, etc.

Is there some explanation available on the difference between these and how they are typically used?

**Comment by hassenius** [comment]
Actually this seems related to #303 and the suggestions in there are very useful... But more would be better again.

**Comment by ecordell** [comment]
The `opm` tool and the guides related to that should be used to build catalogs. The other methods (configmap, appregistry) are maintained only for backwards-compatibility.
