### ISSUE TITLE
non-CSV/CRD yaml files on ConfigMap-based CatalogSource

### ISSUE THREAD

**Issue by miguelsorianod** [operator-framework/operator-registry#325]
Hi,

We have a use-case where we are creating a CatalogSource from a ConfigMap, and among the manifests directory files there are additional ClusterRole yaml files.

Among the fields that I've found in the example ConfigMap https://github.com/operator-framework/operator-registry/blob/master/configmap.example.yaml I can only find 'clusterServiceVersions', 'packages' and 'customResourceDefinitions'.

Is there a way we can make those ClusterRoles be installed automatically too together with the CSV and CRDs using the ConfigMap?

As additional information, we've seen in a community operator that non csv/crd files are included https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/strimzi-kafka-operator/0.17.0 and we have seen that those seem to be included automatically in the InstallPlan. What method is being used there?

Thank you.

**Comment by ecordell** [comment]
ConfigMap based catalogsources do not support additional files. Please use the `opm` tool to build an index that does.

In the future there may be other mechanisms available to support runtime creation of catalog content. The ConfigMap catalog type is currently maintained for backwards-compatibility only
