### ISSUE TITLE
Version reported in v1.12.4 is in-correct 

### ISSUE THREAD

**Issue by IBMRob** [operator-framework/operator-registry#336]
I just downloaded v1.12.4 and then ran version on it and it returns the previous build.

```
$ ~/Downloads/darwin-amd64-opm  version
Version: version.Version{OpmVersion:"1.12.3", GitCommit:"04e4e88", BuildDate:"2020-05-26T15:41:40Z", GoOs:"darwin", GoArch:"amd64"}
```

**Comment by mvalahtv** [comment]
Same for 1.12.5

**Comment by ecordell** [comment]
The release process has since been improved and fixed, and this should no longer be an issue for new releases.
