### ISSUE TITLE
Problem adding index image to local registry without https

### ISSUE THREAD

**Issue by mvalahtv** [operator-framework/operator-registry#368]
Is it possible to add option to `opm index add --http ...` to run http request instead of https? It is needed when local registry has only http enabled (mostly for testing reasons)
```
$ /tmp/operator-test/bin/opm index add -u docker --bundles localhost:5000/test-operator/aqua-operator:v1.0.2 --tag localhost:5000/test-operator/index:latest --from-index localhost:5000/test-operator/index:latest --skip-tls
INFO[0000] building the index                            bundles="[localhost:5000/test-operator/aqua-operator:v1.0.2]"
INFO[0000] Pulling previous image localhost:5000/test-operator/index:latest to get metadata  bundles="[localhost:5000/test-operator/aqua-operator:v1.0.2]"
Error: error resolving name : failed to do request: Head https://localhost:5000/v2/test-operator/index/manifests/latest: http: server gave HTTP response to HTTPS client
```

**Comment by kevinrizza** [comment]
This is already partially implemented, but there are some discrepancies between different pull implementations. This pr https://github.com/operator-framework/operator-registry/pull/310 implements the bulk of the rest of this change (though still not for docker pull), IMO it might be good to resurrect the bits of that pr that would make local testing easier.

**Comment by J0zi** [comment]
Hi @kevinrizza, any update on this?

**Comment by kevinrizza** [comment]
@J0zi Is this a blocking issue? I haven't really had the time or looked too deeply into this, because it should be easy enough to generate and inject certificates into a local registry

**Comment by mvalahtv** [comment]
@kevinrizza Do you mean to start local registry with self sign certificate? And then `--skip-tls` would help? I will try

**Comment by mvalahtv** [comment]
I setup registry with https, but i am getting following error:
```
$ curl  -X GET https://localhost/v2/_catalog --insecure
{"repositories":["test-operator/aqua-operator"]}
$ curl https://localhost:443/v2/test-operator/aqua-operator/tags/list --insecure
{"name":"test-operator/aqua-operator","tags":["v0.0.1","v1.0.0","v0.0.2","v1.0.1","v1.0.2"]}
$ /tmp/operator-test/bin/opm index add -u docker --bundles localhost:443/test-operator/aqua-operator:v1.0.2 --tag localhost:443/test-operator/index:latest --skip-tls
INFO[0000] building the index                            bundles="[localhost:443/test-operator/aqua-operator:v1.0.2]"
ERRO[0000] permissive mode disabled                      bundles="[localhost:443/test-operator/aqua-operator:v1.0.2]" error="error loading bundle from image: error resolving name : failed to do request: Head http://localhost:443/v2/test-operator/aqua-operator/manifests/v1.0.2: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\""
Error: error loading bundle from image: error resolving name : failed to do request: Head http://localhost:443/v2/test-operator/aqua-operator/manifests/v1.0.2: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
Usage:
```
Can you give me hint?

**Comment by mvalahtv** [comment]
Curl with https works fine
```
curl --insecure https://localhost:443/v2/test-operator/aqua-operator/manifests/v1.0.2
{
   "schemaVersion": 1,
   "name": "test-operator/aqua-operator",
   "tag": "v1.0.2",
   "architecture": "amd64",
   "fsLayers": [
...
...
```

**Comment by mvalahtv** [comment]
Hi @kevinrizza, any news on that? It is quite blocker for us now. Thanks

**Comment by kevinrizza** [comment]
Sorry, no, I was suggesting you generate your own certificate and actually use https to interact with the registry. There's real work to plumb all parts of the operator-registry to skip tls. That `skip-tls` flag is currently limited to parts of the image pull, mostly for bundle verification. Is there a reason you can't use https with your test registry?

**Comment by mvalahtv** [comment]
Solved with selfsigned certificate by pointing cacert file. For example
```
export SSL_CERT_FILE=/tmp/certs/domain.crt
```
