### ISSUE TITLE
Single operator in non default channel `opm alpha bundle build` channel issue

### ISSUE THREAD

**Issue by J0zi** [operator-framework/operator-registry#386]
Hi,
looks like a bug
`opm alpha bundle build --directory 0.6.1 --package etcd -t kind-registry:5000/test-operator/etcd:v0.6.1 -b docker 
INFO[0000] Bundle channels information not provided, inferring from parent package directory 
Error: error interpreting channels, please manually input channels instead`

source: https://github.com/J0zi/community-operators/blob/opm-issue/upstream-community-operators/etcd/etcd.package.yaml

as you see, it has a channel

`channels:
- currentCSV: etcdoperator.v0.6.1
  name: alpha
- currentCSV: etcdoperator.v0.9.4
  name: singlenamespace-alpha
- currentCSV: etcdoperator.v0.9.4-clusterwide
  name: clusterwide-alpha
defaultChannel: singlenamespace-alpha
packageName: etcd`

opm version 1.13

**Comment by Bowenislandsong** [comment]
This is an awkward situation where the naming of the CSV is not aligned with what is specified in the `package.yaml`. You are right that `etcdoperator.v0.6.1` should have a channel alpha and should be inferrable. However, inference looks at the `CSV.name` field which specifies `etcdoperator-community.v0.6.1` as the csv name which is not referred directly/indirectly by the package.yaml and therefore the inference failed. The only place where CSV specifies `etcdoperator.v0.6.1` is in the `alm-status-descriptors` label and is not reliable source of inference. 

I don't think this is a bug for the current implementation, but we might need to think about other ways to infer if necessary.

**Comment by J0zi** [comment]
Thank you
