### ISSUE TITLE
opm index add default channel issue

### ISSUE THREAD

**Issue by J0zi** [operator-framework/operator-registry#387]
Hi, we have an issue with  `opm index add` here https://github.com/J0zi/community-operators/blob/RHO-644-cockroachdb/upstream-community-operators/cockroachdb/cockroachdb.package.yaml
 I put everything to channels and opm complains:
`bundles="[kind-registry:5000/test-operator/cockroachdb:v2.0.9 kind-registry:5000/test-operator/cockroachdb:v2.1.1 kind-registry:5000/test-operator/cockroachdb:v2.1.11 kind-registry:5000/test-operator/cockroachdb:v3.0.7]" error="error loading bundle from image: Error adding package error loading bundle into db: no default channel specified for cockroachdb"
Error: error loading bundle from image: Error adding package error loading bundle into db: no default channel specified for cockroachdb`
as you see, default channel is here
command used `/tmp/operator-test/bin/opm index add -u docker --bundles kind-registry:5000/test-operator/cockroachdb:v2.0.9,kind-registry:5000/test-operator/cockroachdb:v2.1.1,kind-registry:5000/test-operator/cockroachdb:v2.1.11,kind-registry:5000/test-operator/cockroachdb:v3.0.7 --tag kind-registry:5000/test-operator/index:latest --mode replaces`

opm version 1.13

**Comment by J0zi** [comment]
looks like there is an issue, that despite default channel defined (3.x), older version is in multiple channels (stable and 2.x) and the tool has no mechanism to set default channel. I propose to use the first one (stable) as default. So contributor can set default by moving package entry up. Could you please @Bowenislandsong have a look? Thank you.

**Comment by Bowenislandsong** [comment]
I think it is up to you which channel should be considered the default. According to the [pacakge.yaml](https://github.com/J0zi/community-operators/blob/RHO-644-cockroachdb/upstream-community-operators/cockroachdb/cockroachdb.package.yaml) it should have been the `stable-3.x`. I assume none of the bundle images in the cmd listed there have the default channel set in there. We expect the first bundle image to contain the default image and then the following bundle images are ok to ignore it unless the default channel is changing. 

I am under the impression that this is related to https://github.com/operator-framework/operator-registry/issues/386. In this case, the `package.yaml` is specifying the correct name and the bundle image should, therefore, infer successfully and contain the default channel. While the default channel is not a required field in generating all bundle images, we should have at least one bundle to point out the default when initializing the package in an index.

**Comment by ecordell** [comment]
https://github.com/operator-framework/operator-registry/pull/503 with this change, the default channel is always specified by the highest semver-version bundle in the package.
