### ISSUE TITLE
Error: no such function: json_remove

### ISSUE THREAD

**Issue by saberkan** [operator-framework/operator-registry#401]
While trying to build an index from a valid generated bundle the following error is showed:
# Check bundle is valide
```
$ opm alpha bundle validate --tag quay.io/saberkan/universal-operator-bundle:v0.1.0
INFO[0000] Create a temp directory at /var/folders/pr/0345pkg953l2tsk930kx28_m0000gn/T/bundle-822367815  container-tool=docker
DEBU[0000] Pulling and unpacking container image         container-tool=docker
INFO[0000] running /usr/local/bin/docker pull quay.io/saberkan/universal-operator-bundle:v0.1.0  container-tool=docker
INFO[0002] running docker create                         container-tool=docker
DEBU[0002] [docker create quay.io/saberkan/universal-operator-bundle:v0.1.0 ]  container-tool=docker
INFO[0002] running docker cp                             container-tool=docker
DEBU[0002] [docker cp b748a5df5ab2350d9c782d3608b8e2d377adde9dd1cbb300b033e6f09693c504:/. /var/folders/pr/0345pkg953l2tsk930kx28_m0000gn/T/bundle-822367815]  container-tool=docker
INFO[0002] running docker rm                             container-tool=docker
DEBU[0002] [docker rm b748a5df5ab2350d9c782d3608b8e2d377adde9dd1cbb300b033e6f09693c504]  container-tool=docker
INFO[0002] Unpacked image layers, validating bundle image format & contents  container-tool=docker
DEBU[0002] Found manifests directory                     container-tool=docker
DEBU[0002] Found metadata directory                      container-tool=docker
DEBU[0002] Getting mediaType info from manifests directory  container-tool=docker
INFO[0002] Found annotations file                        container-tool=docker
INFO[0002] Could not find optional dependencies file     container-tool=docker
DEBU[0002] Validating bundle contents                    container-tool=docker
DEBU[0002] Validating "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition" from file "saberkan.cloud_universalconfigs_crd.yaml"  container-tool=docker
DEBU[0002] Validating "operators.coreos.com/v1alpha1, Kind=ClusterServiceVersion" from file "universal-operator.clusterserviceversion.yaml"  container-tool=docker
INFO[0002] All validation tests have been completed successfully  container-tool=docker

```
# Build index
```
$ opm index add --bundles quay.io/saberkan/universal-operator-bundle:v0.1.3 --tag quay.io/saberkan/operators-index:1.0.0
INFO[0000] building the index                            bundles="[quay.io/saberkan/universal-operator-bundle:v0.1.3]"
Error: no such function: json_remove
Usage:
  opm index add [flags]
```

**Comment by gaohoward** [comment]
I've exact same problem.
I built opm from tag 1.13.3

**Comment by njhale** [comment]
@saberkan @gaohoward Thank you for posting!

How did you build `opm`? are you running the binary on the same machine that you built it on?

**Comment by gaohoward** [comment]
yes. I checked out the tag and build it 
go build ./cmd/opm/
copy the opm binary to my $PATH.
Tried 1.13.* and 1.12.8 so far, same error

**Comment by gaohoward** [comment]
one other thing the opm version gives 'unknown' version info.
[howard@howard a]$ opm version
Version: version.Version{OpmVersion:"unknown", GitCommit:"", BuildDate:"", GoOs:"linux", GoArch:"amd64"}

**Comment by njhale** [comment]
@gaohoward you're going to want to run `make build` to get the proper build-tags. Let me know if that helps.

**Comment by gaohoward** [comment]
Thanks @njhale . Update:
I found that Fedora31 + 1.12.7 somehow works. Other versions from 1.11.1 to 1.13.3 and master not working (most 1.12.x has fragmentation violation fault) on Fedora 27 (my current env). 
Also I tried building opm 1.12.7 on F31 and the version info still missing:

`[howard@localhost a]$ make build
GOFLAGS="-mod=vendor" go build  -o bin/appregistry-server ./cmd/appregistry-server
GOFLAGS="-mod=vendor" go build  -o bin/configmap-server ./cmd/configmap-server
GOFLAGS="-mod=vendor" go build  -o bin/initializer ./cmd/initializer
GOFLAGS="-mod=vendor" go build  -o bin/registry-server ./cmd/registry-server
GOFLAGS="-mod=vendor" go build -ldflags "-X 'github.com/operator-framework/operator-registry/cmd/opm/version.gitCommit=b557bda' -X 'github.com/operator-framework/operator-registry/cmd/opm/version.opmVersion=1.12.7' -X 'github.com/operator-framework/operator-registry/cmd/opm/version.buildDate=2020-07-30T02:33:59Z'"  -o bin/opm ./cmd/opm
`
and here is the output:

`[howard@localhost a]$ ./opm version
Version: version.Version{OpmVersion:"unknown", GitCommit:"", BuildDate:"", GoOs:"linux", GoArch:"amd64"}
`

**Comment by saberkan** [comment]
@njhale, the issue occurred for me because I was building opm as `go build ./cmd/opm/` on mac os.
Building with `make build` fixed my issue.  Thank you.
