### ISSUE TITLE
opm --mode semver-skippatch does not allow channel switching

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-registry#431]
**Summary**
We've built a channel taxonomy following the pattern:  vX.Y as follows:

| ver  | replaces | skipRange | channels | defaultChannel |
|---|---|---|---|---|
| 1.0.0  | | | v1.0  | v1.0 |
| 1.0.1  | 1.0.0 | <1.0.1 | v1.0 | v1.0  |
| 1.1.0  |  | <1.1 | v1.1 | v1.1  |

When used with the default `--mode replaces`, this allows the user to choose the v1.0 channel, which will install operator 1.0.1 and then switch to the v1.1 channel, which allows the operator to upgrade to 1.1.0.

If I remove replaces and olm.skipRange from the CSV's and rely solely on `--mode semver.skipPatch`, I no longer have the ability to switch channels.

| ver  | replaces | skipRange | channels | defaultChannel |
|---|---|---|---|---|
| 1.0.0  | | |  | v1.0 |
| 1.0.1  | |  | v1.0 | v1.0  |
| 1.1.0  | | | v1.1 | v1.1  |

It appears that I need to use both `olm.skipRange` AND `--mode semver-skippatch` to achieve the same behavior as I did using replaces.  If I do this, it works with `--mode semver-skippatch`:

| ver  | replaces | skipRange | channels | defaultChannel |
|---|---|---|---|---|
| 1.0.0  | | | v1.0  | v1.0 |
| 1.0.1  | | <1.0.1 | v1.0 | v1.0  |
| 1.1.0  |  | <1.1 | v1.1 | v1.1  |

Per a call on the August 27th olm-dev call, we discussed this and it looks like the channels were not considered when building the graph.

cc: @kevinrizza @ecordell

**Comment by cdjohnson** [comment]
Can you confirm that this is working as designed and I need to continue using `olm.skipRange`?  or is this a bug?

I'm happy that `replaces` isn't needed as that would indeed be a problem.

**Comment by ecordell** [comment]
Correct, right now adding only adds to one channel at a time.

It would make sense to allow you to specify a list of channels (or all channels), and get the behavior as if you had added to each separately. 

We've also been discussing a way to promote between channels without publishing a new bundle, which might make more sense for other channel modes (i.e. fast/stable)

**Comment by exdx** [comment]
Closing for now, as the new Declarative Config-based indexes should help building custom graphs between dependencies.
