### ISSUE TITLE
upstream-registry-builder size seems too large

### ISSUE THREAD

**Issue by jmccormick2001** [operator-framework/operator-registry#438]
doppio:[~] podman images  | grep upstream
quay.io/operator-framework/upstream-registry-builder                                                     latest   d6ecbf195274  2 days ago    1.32 GB

this seems wrong to me?  am I correct or is this normally supposed to be this size.

**Comment by benluddy** [comment]
Not sure, but it's mostly build cruft. I opened a PR (https://github.com/operator-framework/operator-registry/pull/439) to use a multi-stage build and the resulting image is about half the size.

**Comment by jmccormick2001** [comment]
I might try to test that out, this image size came to my attention in an interesting way, I was trying to test something that uses this image on a CRC built Openshift instance, in crc there is some sort of image download size being enforced which causes this image to not be pulled down.

**Comment by jmccormick2001** [comment]
the image size with the PR does indeed drop by over half in my testing to somewhere around 450Mb.  I'd suspect people that heavily use this image will like seeing that size reduced.

**Comment by benluddy** [comment]
Thanks for noticing and reporting this.
