### ISSUE TITLE
Opm alpha bundle build is failing on mixed (bundle and package) format

### ISSUE THREAD

**Issue by J0zi** [operator-framework/operator-registry#440]
Hi,

we are preparing operator-framework pipelines to accept bundle format. So we [simulated](https://github.com/J0zi/community-operators/tree/RHO-713-bundle-in-travis/community-operators/prometheus) a situation, where new operator version is in bundle manifest format. Old versions remains in package manifest format.

It is blocking us for supporting bundle format.

`opm alpha bundle build` is searching over CSVs for all versions and [crashes](https://travis-ci.com/github/J0zi/community-operators/jobs/384033223#L3537) on bundle version. As there is no CSV in version directory. CSV is actually deeper, under `maifests` directory. So the command is unable to build bundle from package manifest when bundle manifest is present in a newer version.

Maybe some hint, you can detect format by checking if `annotation.yml` is present and then search CSV according the version.

`cmd:` '/tmp/operator-test/bin/opm alpha bundle build --directory 0.14.0 --package prometheus -t kind-registry:5000/test-operator/prometheus:v0.14.0 -b docker '
  delta: '0:00:00.777233'
  end: '2020-09-11 19:12:10.813383'
  failed_when_result: false
  msg: non-zero return code
  rc: 1
  start: '2020-09-11 19:12:10.036150'
  stderr: |-
    time="2020-09-11T19:12:10Z" level=info msg="Bundle channels information not provided, inferring from parent package directory"
    Error: please manually input channels and packageName, error interpreting bundle from directory /tmp/operator-test/operator-bundle/src/prometheus/0.14.0, error geting CSVs from bundles in the package directory, no ClusterServiceVersion object found in /tmp/operator-test/operator-bundle/src/prometheus/0.38.0`

Thank you.

**Comment by gallettilance** [comment]
IMO you should either completely be in the new format or not be at all. You can rely on the presence or absence of the package.yaml file to detect which format the directory is in and whether to run the conversion.

**Comment by kevinrizza** [comment]
@J0zi I don't think we ever built the backwards compatible mode of `opm alpha bundle build` with a mixed format like this in mind. We could potentially do something for now like ignore any folders in the directory that aren't in the old format.

I'm curious though, why is this a blocker? Shouldn't these bundles be built just once? If so, can't you just build them before any new format bundles are merged into the repository at all?

**Comment by J0zi** [comment]
Thank you, we will definitely request our contributors to use only one type. Bundle or package. No mixture. Thank you.
