### ISSUE TITLE
opm providing a means to inspect an image

### ISSUE THREAD

**Issue by rrati** [operator-framework/operator-registry#450]
Using opm in a CI/CD pipeline is difficult because CSV versions will be autogenerated making it difficult to know what should be placed into the replaces field in a CSV.

Similarly knowing the image tag of a the previous catalog image to be used with --from-index is similarly difficult.

It would be great if opm provided a means to produce information to help identify previous versions for bundle/catalog generation in CI/CD pipelines.

**Comment by ecordell** [comment]
`opm registry serve` will expose a grpc interface over the contents of the catalog, which can be queried to determine existing versions.

There is an in-flight enhancement that would make the registry content generally easier to consume in this kind of environment: https://github.com/operator-framework/enhancements/pull/26.
