### ISSUE TITLE
[RFE] Declarative OPM config

### ISSUE THREAD

**Issue by kevinrizza** [operator-framework/operator-registry#467]
## Feature Request

**Is your feature request related to a problem? Please describe.**
As an operator pipeline administrator, I would like to have more fine control over exactly what is included in an index image.

**Why is this important:** 
Index images currently are only built via metadata included in bundle images to define and modify package level updates, as well as to define what versions are included in the package. Because the only trivial way of including more data is to append to the front of a package, if something needs to be modified, updated or removed there is no easy way to do that today.

**Describe the solution you'd like**
- A user can inspect an existing index image to determine what package versions are available as well as any other metadata associated with the package or the index as a whole
- A user can modify package and index level metadata to redefine the content that is in the index

Current work in progress: https://github.com/operator-framework/enhancements/pull/37

**Comment by dinhxuanvu** [comment]
This feature has been completed as it is in the current codebase.
/close

**Comment by kevinrizza** [comment]
this is very out of date. closing
