### ISSUE TITLE
Latest version of operator-registry image complains about v1alpha1 API version in CRDs

### ISSUE THREAD

**Issue by pmorie** [operator-framework/operator-registry#50]
After pulling the latest operator-registry image and pointing it at a previously-good directory, the log contains tons of messages of this form:

```
time="2019-05-22T13:23:35Z" level=info msg="could not decode contents of file manifests/cluster-federation/0.0.10/cluster-registry.crd.yaml into package: error unmarshaling JSON: v1alpha1 is not in dotted-tri fo
rmat" dir=manifests file=cluster-registry.crd.yaml load=bundles  
```

At a minimum, this is a confusing red herring. The `docker build` this was part of completed fine, adding to the confusion.

**Comment by chancez** [comment]
I also am seeing this, but only when I have a nested bundle with more than 1 directory.

**Comment by njhale** [comment]
Closing because I haven't seen this issue and various fixes and improvements have been merged since this was reported. Please re-open if you notice this on master.
