### ISSUE TITLE
[MacOs] opm v1.15.1 fails to create catalog source index (go-sqlite3 requires cgo)

### ISSUE THREAD

**Issue by bfabec** [operator-framework/operator-registry#518]
With the latest version v1.15.1 of the opm command from the [release page](https://github.com/operator-framework/operator-registry/releases/tag/v1.15.1), the darwin-amd64 (mac) version produces an error when running the index add command.  However, this works fine with the linux amd64 binary.

```
opm.v1.15.1 index add -c docker --bundles docker.io/ibmcom/ibm-watson-aiops-bundle:bfabec --mode replaces --from-index docker.io/ibmcom/ibm-watson-aiops-catalog:1.0.0-20200925140829 --tag docker.io/ibmcom/ibm-watson-aiops-catalog:bfabec
INFO[0000] building the index                            bundles="[docker.io/ibmcom/ibm-watson-aiops-bundle:bfabec]"
INFO[0000] Pulling previous image docker.io/ibmcom/ibm-watson-aiops-catalog:1.0.0-20200925140829 to get metadata  bundles="[docker.io/ibmcom/ibm-watson-aiops-bundle:bfabec]"
INFO[0000] running /usr/local/bin/docker pull docker.io/ibmcom/ibm-watson-aiops-catalog:1.0.0-20200925140829  bundles="[docker.io/ibmcom/ibm-watson-aiops-bundle:bfabec]"
INFO[0004] running /usr/local/bin/docker pull docker.io/ibmcom/ibm-watson-aiops-catalog:1.0.0-20200925140829  bundles="[docker.io/ibmcom/ibm-watson-aiops-bundle:bfabec]"
INFO[0006] Getting label data from previous image        bundles="[docker.io/ibmcom/ibm-watson-aiops-bundle:bfabec]"
INFO[0006] running docker inspect                        bundles="[docker.io/ibmcom/ibm-watson-aiops-bundle:bfabec]"
INFO[0006] running docker create                         bundles="[docker.io/ibmcom/ibm-watson-aiops-bundle:bfabec]"
INFO[0006] running docker cp                             bundles="[docker.io/ibmcom/ibm-watson-aiops-bundle:bfabec]"
INFO[0058] running docker rm                             bundles="[docker.io/ibmcom/ibm-watson-aiops-bundle:bfabec]"
Error: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

**Comment by tpneal** [comment]
We are seeing similar with opm v1.15.1 on ppc64le too.
[hcluser@amber-ahp-build-powerle ~]$ opm index add --bundles ibmcom/ucds-operator-bundle@sha256:08c87efeb6c3bf10d3333e18c3aeadfa60ee6a2e7ec57d464b83afbecb49afe5 --from-index ibmcom/ucds-operator-catalog:latest --tag cp.stg.icr.io/cp/ucds-operator-catalog:2.0.1-ppc64le -c podman
INFO[0000] building the index                            bundles="[ibmcom/ucds-operator-bundle@sha256:08c87efeb6c3bf10d3333e18c3aeadfa60ee6a2e7ec57d464b83afbecb49afe5]"
INFO[0000] Pulling previous image ibmcom/ucds-operator-catalog:latest to get metadata  bundles="[ibmcom/ucds-operator-bundle@sha256:08c87efeb6c3bf10d3333e18c3aeadfa60ee6a2e7ec57d464b83afbecb49afe5]"
INFO[0000] running /usr/bin/podman pull ibmcom/ucds-operator-catalog:latest  bundles="[ibmcom/ucds-operator-bundle@sha256:08c87efeb6c3bf10d3333e18c3aeadfa60ee6a2e7ec57d464b83afbecb49afe5]"
INFO[0006] running /usr/bin/podman pull ibmcom/ucds-operator-catalog:latest  bundles="[ibmcom/ucds-operator-bundle@sha256:08c87efeb6c3bf10d3333e18c3aeadfa60ee6a2e7ec57d464b83afbecb49afe5]"
INFO[0012] Getting label data from previous image        bundles="[ibmcom/ucds-operator-bundle@sha256:08c87efeb6c3bf10d3333e18c3aeadfa60ee6a2e7ec57d464b83afbecb49afe5]"
INFO[0012] running podman inspect                        bundles="[ibmcom/ucds-operator-bundle@sha256:08c87efeb6c3bf10d3333e18c3aeadfa60ee6a2e7ec57d464b83afbecb49afe5]"
INFO[0012] running podman create                         bundles="[ibmcom/ucds-operator-bundle@sha256:08c87efeb6c3bf10d3333e18c3aeadfa60ee6a2e7ec57d464b83afbecb49afe5]"
INFO[0012] running podman cp                             bundles="[ibmcom/ucds-operator-bundle@sha256:08c87efeb6c3bf10d3333e18c3aeadfa60ee6a2e7ec57d464b83afbecb49afe5]"
INFO[0015] running podman rm                             bundles="[ibmcom/ucds-operator-bundle@sha256:08c87efeb6c3bf10d3333e18c3aeadfa60ee6a2e7ec57d464b83afbecb49afe5]"
Error: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
Usage:
  opm index add [flags]

**Comment by bfabec** [comment]
Seems related to https://github.com/operator-framework/operator-registry/issues/510

**Comment by ecordell** [comment]
I believe this is fixed in the latest release - could you try again with 1.15.3 and report back?

Closing optimistically, please re-open if you still find this to be an issue.
