### ISSUE TITLE
Adding bundle to index image prior to 1.12.8 results in corrupted dependencies

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-registry#519]
**Problem:**
We have several catalog index images in docker.io that have been created with opm version 1.12.3.

When we add any new bundle with a new channel to this index via `opm index add` or `opm registry add`, a migration of the `dependencies` table occurs, which overlays all of the `values` entries for all existing dependency entries to the first entry's value.

This results in OLM not correctly resolving any of the dependent operators from a previous channel.

**For example:**  
Examining the database from this catalog index image:
ibmcom/ibm-cp-integration-catalog:1.0.2-2020-09-30-1247-e04dfaea

Results in:
type | value | operatorbundle_name | operatorbundle_version | operatorbundle_path
-- | -- | -- | -- | --
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"integration.ibm.com","kind":"OperationsDashboard","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"integration.ibm.com","kind":"PlatformNavigator","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"integration.ibm.com","kind":"AssetRepository","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"appconnect.ibm.com","kind":"Dashboard","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"datapower.ibm.com","kind":"DataPowerService","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"eventstreams.ibm.com","kind":"EventStreams","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"hsts.aspera.ibm.com","kind":"IbmAsperaHsts","type":"olm.gvk","version":"v1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"mq.ibm.com","kind":"QueueManager","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"datapower.ibm.com","kind":"DataPowerService","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"integration.ibm.com","kind":"OperationsDashboard","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"integration.ibm.com","kind":"PlatformNavigator","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"integration.ibm.com","kind":"AssetRepository","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"appconnect.ibm.com","kind":"Dashboard","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"eventstreams.ibm.com","kind":"EventStreams","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"hsts.aspera.ibm.com","kind":"IbmAsperaHsts","type":"olm.gvk","version":"v1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"mq.ibm.com","kind":"QueueManager","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"integration.ibm.com","kind":"AssetRepository","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"eventstreams.ibm.com","kind":"EventStreams","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"integration.ibm.com","kind":"OperationsDashboard","type":"olm.gvk","version":"v1beta2"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"mq.ibm.com","kind":"QueueManager","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"appconnect.ibm.com","kind":"Dashboard","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"datapower.ibm.com","kind":"DataPowerService","type":"olm.gvk","version":"v1beta2"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"hsts.aspera.ibm.com","kind":"IbmAsperaHsts","type":"olm.gvk","version":"v1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"integration.ibm.com","kind":"PlatformNavigator","type":"olm.gvk","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd

If I attempt to add a bundle image with a new channel to the database using `opm registry add`, the database is as follows:

type | value | operatorbundle_name | operatorbundle_version | operatorbundle_path
-- | -- | -- | -- | --
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.0 | 1.0.0 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:1a9b7cde0627b1901b8583c3e5c0cd6fe5aebb163c9e0b34629f60828e951dac
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.1 | 1.0.1 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:d672a0da3beac0c527da9012a7f5c7492a6f8de0117ea600efeae0bf7f3ac897
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.0.2 | 1.0.2 | docker.io/ibmcom/ibm-cp-integration-bundle@sha256:a1955c7a6eaa8f00c11d7e1d4e16e4a94e1ed76c56e5d2134629bf4ed03210bd
olm.gvk | {"group":"appconnect.ibm.com","kind":"Dashboard","version":"v1beta1"} | ibm-cp-integration.v1.1.0 | 1.1.0 | hyc-cdjohnson-team-docker-local.artifactory.swg-devops.com/cdjohnson/ibm-cp-integration-bundle:cdjohnson4
olm.gvk | {"group":"datapower.ibm.com","kind":"DataPowerService","version":"v1beta2"} | ibm-cp-integration.v1.1.0 | 1.1.0 | hyc-cdjohnson-team-docker-local.artifactory.swg-devops.com/cdjohnson/ibm-cp-integration-bundle:cdjohnson4
olm.gvk | {"group":"management.apiconnect.ibm.com","kind":"ManagementCluster","version":"v1beta1"} | ibm-cp-integration.v1.1.0 | 1.1.0 | hyc-cdjohnson-team-docker-local.artifactory.swg-devops.com/cdjohnson/ibm-cp-integration-bundle:cdjohnson4
olm.gvk | {"group":"integration.ibm.com","kind":"OperationsDashboard","version":"v1beta2"} | ibm-cp-integration.v1.1.0 | 1.1.0 | hyc-cdjohnson-team-docker-local.artifactory.swg-devops.com/cdjohnson/ibm-cp-integration-bundle:cdjohnson4
olm.gvk | {"group":"integration.ibm.com","kind":"PlatformNavigator","version":"v1beta1"} | ibm-cp-integration.v1.1.0 | 1.1.0 | hyc-cdjohnson-team-docker-local.artifactory.swg-devops.com/cdjohnson/ibm-cp-integration-bundle:cdjohnson4
olm.gvk | {"group":"mq.ibm.com","kind":"QueueManager","version":"v1beta1"} | ibm-cp-integration.v1.1.0 | 1.1.0 | hyc-cdjohnson-team-docker-local.artifactory.swg-devops.com/cdjohnson/ibm-cp-integration-bundle:cdjohnson4
olm.gvk | {"group":"integration.ibm.com","kind":"AssetRepository","version":"v1beta1"} | ibm-cp-integration.v1.1.0 | 1.1.0 | hyc-cdjohnson-team-docker-local.artifactory.swg-devops.com/cdjohnson/ibm-cp-integration-bundle:cdjohnson4
olm.gvk | {"group":"eventstreams.ibm.com","kind":"EventStreams","version":"v1beta1"} | ibm-cp-integration.v1.1.0 | 1.1.0 | hyc-cdjohnson-team-docker-local.artifactory.swg-devops.com/cdjohnson/ibm-cp-integration-bundle:cdjohnson4

**Potential problem:**
This appears to be the faulty query:
https://github.com/operator-framework/operator-registry/blob/master/pkg/sqlite/migrations/009_properties.go#L78-L83

**Workaround:**
Rebuild the entire index from each bundle index in the `operatorbundles` table, avoiding the migration query.

**Comment by cdjohnson** [comment]
The problem with the query is that it assumes that the `operatorbundle_name` is unique.  In the failing case, an Operator bundle has >1 `olm.gvk` entries.  So the query must instead iterate through each entry rather than relying on an inner-join to self.

**Comment by jdockter** [comment]
@njhale any news on this?

**Comment by ecordell** [comment]
This should be fixed in newer releases - do you see this in 1.15.3? 

Closing optimistically but please re-open if this is still an issue.
