### ISSUE TITLE
Add hashes for release binaries

### ISSUE THREAD

**Issue by font** [operator-framework/operator-registry#526]
This issue is to add sha-256 hashes for the release binaries to provide some basic level of confidence that the binaries have not been tampered with.

**Comment by exdx** [comment]
Relates to #654 -- producing release artifacts

**Comment by exdx** [comment]
We have started doing this on the OLM repository release.

**Comment by joelanford** [comment]
This is addressed in #710

**Comment by joelanford** [comment]
#710 ended up merging without changing the mechanism for release binary uploads. Therefore this issue is still relevant.
