### ISSUE TITLE
Index fails when using docker as tool

### ISSUE THREAD

**Issue by wtrocki** [operator-framework/operator-registry#534]
When executing index command 
```
opm index add --build-tool=docker --bundles quay.io/fdsfsd/fdsfsdf-bundle:0.1.0 --tag quay.io/fsdfsdf/sdfsdf-index
```

Response
```
The push refers to repository [docker.io/library/fdsfsdf-index]
An image does not exist locally with the tag: fdsfsdf-index
```

Expected response:
```
fdsfsdf-index:0.1.0 was created
```

**Comment by ankitathomas** [comment]
I've tried replicating this with both a single valid bundle and an empty bundle list. With docker 20.10.1 and opm v1.15.3, trying to create a new index image without the tag creates an index with the latest tag.

$ docker images
REPOSITORY                                        TAG       IMAGE ID       CREATED              SIZE
quay.io/ankitathomas/index-2                      latest    c83661eb9174   43 seconds ago       68.3MB

As long as the remote repository exists on quay, the subsequent push will work. This doesn't look like an opm bug

**Comment by wtrocki** [comment]
@ankitathomas Thank you. 

> As long as the remote repository exists on quay, the subsequent push will work.

That might be it. It was probably because I was about to create new image on quay.
