### ISSUE TITLE
permission denied in custom catalog pod

### ISSUE THREAD

**Issue by ryandawsonuk** [operator-framework/operator-registry#553]
The pod for my custom catalog is giving this error:
```
Error: open db-254798428: permission denied
Usage:
  opm registry serve [flags]
```
This is the whole error. Not sure why this has just started happening. Presumably I've changed something but it's hard to tell from the error what I could have changed.

**Comment by ryandawsonuk** [comment]
I've tried adding extra permission to the service account but it's not making any difference.

**Comment by ryandawsonuk** [comment]
Now tried the same CatalogSource on a new openshift cluster and it works there. Problem must be a permission change that I made to the other cluster.

**Comment by ecordell** [comment]
@ryandawsonuk did you determine what the root cause was? We may be missing a requirement that we need to document.

**Comment by ecordell** [comment]
Please open a new issue with more details if you have time to find them. Thanks!

**Comment by ryandawsonuk** [comment]
@ecordell I actually just found out some more about this. It's not caused by the permissions change above. I created a new cluster and had everything working. Then I installed [argo](https://deploy.seldon.io/docs/getting-started/production-installation/argo/)  and [minio](https://deploy.seldon.io/docs/getting-started/production-installation/minio/) and now I've got the problem above again.

I will try removing what I've installed and let you know. Currently suspecting something that the argo install does but not sure what.

**Comment by ryandawsonuk** [comment]
Yeah deleting those installs got it working again.

Problem is not argo. It's the helm install of the minio helm chart. When that helm chart is installed (in the minio-system namespace) then I get the above error in the catalog pod.

The minio helm chart [does support deployment to openshift](https://github.com/minio/charts/pull/48). Actually I can use the minio features successfully. Minio looks happy. The problem is that it breaks my catalog pod somehow.

**Comment by ryandawsonuk** [comment]
Given that this is a permissions error it is probably caused by [those SecurityContextConstraints](https://github.com/minio/charts/blob/2c7243c66451cab25ac194c6a56c2c18c006f42a/minio/templates/securitycontextconstraints.yaml#L3).

@ecordell now not sure whether to raise an issue here or with minio. Maybe the authors of that PR will have a view. @Arano-kai ? @harshavardhana ?

**Comment by harshavardhana** [comment]
@ryandawsonuk for openshift it is required you create all the security constraints and role bindings properly to use this feature. 

> Error: open db-254798428: permission denied
> Usage:
>   opm registry serve [flags]

The error here is that `opm registry` doesn't have read permissions to the file that you are pointing to.
