### ISSUE TITLE
Deprecate/remove opm alpha bundle commands

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-registry#561]
As discussed, SDK is the tool that has the goal to help users to integrate their projects with OLM and in this way, create/update/validate/test bundles when OPM has the goal to help users which needs do more complex tasks regards the index catalogue. 

So, shows reasonable at this moment we no longer have these commands and the need to keep them maintained. Since it is in alpha shows that we can remove them directly.

**Comment by exdx** [comment]
Closing as related PR was closed (see PR for resolution).
