### ISSUE TITLE
Detect common invalid annotations:  e.g. olm.skiprange

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-registry#568]
It's a very common problem to accidentally use the annotation `olm.skiprange` instead of `olm.skipRange`.  It can take days or weeks for a new developer to not understand why their operators will never upgrade to a new channel.

It would be very helpful for new developers if `opm <index|registry> add` would simply detect some of the most common errors like this.

**Comment by cdjohnson** [comment]
Discussed in the OLM Feature Planning meeting today a bit. They suggested that this be fixed in the API repo here:
https://github.com/operator-framework/api/tree/master/pkg/validation

**Comment by jchunkins** [comment]
@cdjohnson Regarding your warning comment: 

> Need to be careful that the validation doesn't happen in OLM and only in OPM

At the moment `ClusterServiceVersionValidator` is the validator that is responsible for checking CSV validity. If you do a search for this across all repos in the operator-framework organization like this:

https://github.com/search?q=org%3Aoperator-framework+ClusterServiceVersionValidator&type=code

You will see that the only projects that use this are:

- operator-framework/operator-sdk
- operator-framework/operator-registry

Given the scope of your concern, we can ignore `operator-framework/operator-sdk`, leaving only usage within `operator-framework/operator-registry`.

From within the operator-framework/operator-registry the `ClusterServiceVersionValidator` is used in function `ValidateBundleContent`. This is a function that is part of the `BundleImageValidator` interface. You can see uses of this in this query:
 
https://github.com/search?q=org%3Aoperator-framework+ValidateBundleContent&type=code

It's used in calls such as:

- opm alpha bundle unpack
- opm alpha bundle validate

I don't see any initializer or registry-server usage of this validation logic, so I think we're OK with making changes in `ClusterServiceVersionValidator` as needed.
