### ISSUE TITLE
OPM - Alpine Linux Support

### ISSUE THREAD

**Issue by kodi1981** [operator-framework/operator-registry#602]
The OPM binary is not working for alpine Linux. Do have support for alpine?

**Comment by joelanford** [comment]
Can you please provide more information about what's not working? Do you have an error message or log output you could provide?

Thanks!

**Comment by joelanford** [comment]
If this is a musl vs glibc problem, we currently have a requirement for CGO_ENABLED=1 to support linking for sqlite libraries.

We're planning to remove sqlite in the future so this problem will hopefully go away eventually (not saying we won't help come up with a solution in the meantime).

**Comment by kodi1981** [comment]
@joelanford  
If we want to build the OPM binary for Alpine, what would be the Parameters to build it.

```
Example for Darwin 
GOOS=darwin CC=o64-clang CXX=o64-clang++ CGO_ENABLED=1 $(GO) build $(opm_version_flags) $(TAGS) -o "bin/darwin-amd64-opm" --ldflags "-extld=o64-clang" ./cmd/opm
```

**Comment by benluddy** [comment]
You should be able to run `make bin/opm` on Alpine -- I pulled down the current `golang:alpine` image from Docker Hub, ran `apk add build-base sqlite-dev git`, cloned operator-registry, then ran `make bin/opm`, and it seems to work. I'm guessing that the important difference is glibc vs. musl libc (as @joelanford guessed).

**Comment by joelanford** [comment]
It looks like your original question has been answered, so I'm closing this out. Please open a new issue if you're unable to build `opm` on alpine with the provided instructions.
