### ISSUE TITLE
make opm arch-aware and build multi-arch manifested ose-operator-registry with base images for s390x, arm64 and ppc64le architectures

### ISSUE THREAD

**Issue by cfilleke** [operator-framework/operator-registry#654]
Currently, opm references an upstream amd64 image by default, and these images are not built, manifested or maintained upstream for other architectures. This poses[ a particular issue in the testing of pre-release disconnected OLM install procedures](https://bugzilla.redhat.com/show_bug.cgi?id=1955945), and[ an additional step for air-gapped customers on Z and P platforms](https://docs.openshift.com/container-platform/4.7/operators/admin/olm-restricted-networks.html). 

In order for opm in particular, and operator registry maintenance to be multi-arch and arch agnostic,  opm would need to be arch-aware (picking up on which architecture it's running on or being invoked on behalf of), and to reference a base multi-arch manifest that has images in it built for s390x, arm64 and ppc64le as well as amd64. 

In the absence of build hardware to build and test the multi-arch base images on, the new features in buildah and podman developed by @rhatdan included in Fedora Core 34 and RHEL 8.4  allows [cross-builds of containers](https://cfillekes-25575.medium.com/building-and-publishing-multi-arch-images-and-image-manifests-with-red-hat-buildah-and-podman-927c717adaf3) and [cross compiles of applications](https://cfillekes-25575.medium.com/buildah-as-cross-compiler-6844e8ea136) for these architectures by enabling the --platform flag.  I've tested this in FC34 and am looking forward to testing it in RHEL 8.4 -- and possibly even applying these methods to build the  manifested ose-operator-registry with base images for s390x, arm64 and ppc64le architectures -- feel free to assign me to this task. :)  I have access to Z and P server systems to test the cross-builds of this container. Thanks.

**Comment by kevinrizza** [comment]
Is it possible to build a github action using a fedora base image with that feature? At one time we were building for s390x upstream, but we needed to disable it because we ran into environment issues that made it difficult to maintain.

**Comment by joelanford** [comment]
There's a related issue in the OLM repo here: https://github.com/operator-framework/operator-lifecycle-manager/issues/2079

Just for reference, operator-sdk builds multi-platform base images from a github action: https://github.com/operator-framework/operator-sdk/blob/82db4d4a32ec59071dc0afeefc3fdeba2372033b/.github/workflows/deploy.yml#L66-L112

Anything we could reuse from there?

**Comment by exdx** [comment]
Hi @cfilleke , we would be happy to accept new contributors if you are interesting in helping us overhaul our release/build process and support more architectures with our releases. The `#olm-dev` slack channel on the kubernetes slack is a good place to discuss these types of issues. 

See the above comment for an example of the type of cross-platform build that we would want in this project (and across other OLM projects as well). If you are interested in helping develop this type of registry build across different architectures, we can assign this issue to you as you suggested.

**Comment by joelanford** [comment]
We assigned this to me just so I can help keep track. If you're interested in taking this on, let me know and I can re-assign (and help answer any questions you might have).

Another related issue is https://github.com/operator-framework/operator-lifecycle-manager/issues/2118

**Comment by joelanford** [comment]
Addressed in #710

**Comment by cfilleke** [comment]
LMK when we can get together and test the results on Power & Z platforms.  Lookin good.  Thanks @joelanford

**Comment by joelanford** [comment]
Multi-arch images are now available at `quay.io/operator-framework/olm`, so closing this out. 🎉 

The next minor release of `opm` will include tags for `latest` and tracking minor releases.

@cfilleke Please open a new issue if you find any issues testing this on Power and Z platforms.
