### ISSUE TITLE
Removing a non-existent operator from an index image does not produce an error or a warning message

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/operator-registry#675]
When supplying a list of non-existent operator(s) from an index image to `opm index rm`, the command results in a successful run and no logs are produced that warn those supplied operators (s) don't exist.

This is tracking the UX improvement to at least warn users that these operator(s) don't exist.

Mirror of https://bugzilla.redhat.com/show_bug.cgi?id=1913644

**Comment by akihikokuroda** [comment]
I would like to fix this.  Would you assign to me?  Thanks!

**Comment by dinhxuanvu** [comment]
Waiting for the pending PR to be reviewed and merged before closing out this issue.
