### ISSUE TITLE
Unknown version of `opm` in `upstream-opm-builder:latest`

### ISSUE THREAD

**Issue by msugakov** [operator-framework/operator-registry#681]
Hello,

I'm debugging `imagePullSecrets` problems during `operator-sdk run bundle` (possibly unrelated problem) and noticed that `upstream-opm-builder` image brings `opm` that cannot report its version normally:

```bash
$ docker run --rm -it quay.io/operator-framework/upstream-opm-builder:latest opm version
Version: version.Version{OpmVersion:"unknown", GitCommit:"", BuildDate:"", GoOs:"linux", GoArch:"amd64"}
```

Compare it with what `opm` binary manually downloaded from GitHub releases reports about itself

```bash
$ opm version
Version: version.Version{OpmVersion:"v1.17.3", GitCommit:"b660eab", BuildDate:"2021-06-03T09:58:23Z", GoOs:"linux", GoArch:"amd64"}
```

Spot-checked few other `upstream-opm-builder` tags from https://quay.io/repository/operator-framework/upstream-opm-builder?tab=tags and they all report `OpmVersion:"unknown"`.

Is this expected?

**Comment by msugakov** [comment]
This is already mentioned in https://github.com/operator-framework/operator-registry/issues/403

**Comment by exdx** [comment]
Seems like that Dockerfile is out of date and should be updated

**Comment by joelanford** [comment]
Also possibly related to #526 and #654, where we're thinking of making improvements to the upstream release process.

**Comment by joelanford** [comment]
This is addressed in #710, with the exception that #710 as is would make this fix in a new image repo (quay.io/operator-framework/opm)

**Comment by joelanford** [comment]
Closing, the new multi-arch images are available at `quay.io/operator-framework/opm` and has the correct version strings

```
$ docker run --rm -it quay.io/operator-framework/opm:v1.18.0 version
Version: version.Version{OpmVersion:"v1.18.0", GitCommit:"b8268490", BuildDate:"2021-08-11T19:07:54Z", GoOs:"linux", GoArch:"arm64"}
```

**Comment by msugakov** [comment]
Do you also plan to update `quay.io/operator-framework/upstream-opm-builder` image?
It still prints unknown version
```bash
$ docker run --rm -it quay.io/operator-framework/upstream-opm-builder:latest opm version
Version: version.Version{OpmVersion:"unknown", GitCommit:"", BuildDate:"", GoOs:"linux", GoArch:"amd64"}
```
I think this image is used by upstream OLM when deploying operator on the cluster.

**Comment by joelanford** [comment]
There's no plan to change the build configuration for `quay.io/operator-framework/upstream-opm-builder`. We will likely deprecate that image, so tools relying on it should move to `quay.io/operator-framework/opm`

In this case, `operator-sdk run bundle` should be updated to use this image.

**Comment by msugakov** [comment]
Is there an issue for this already or does it deserve one?

**Comment by msugakov** [comment]
The same happens with index images. Here's an example of community operators

```bash
$ docker run --rm -it quay.io/operatorhubio/catalog:latest version                                                  
Version: version.Version{OpmVersion:"unknown", GitCommit:"", BuildDate:"", GoOs:"linux", GoArch:"amd64"}
```
