### ISSUE TITLE
Unable to run e2e locally on Mac: exec format error

### ISSUE THREAD

**Issue by akihikokuroda** [operator-framework/operator-registry#784]
I ran the [e2e test of operator-registry](https://github.com/operator-framework/operator-registry/blob/master/docs/contributors/e2e_tests.md#kind-without-ssl)  with
DOCKER_REGISTRY_HOST=localhost:5000 make build e2e SKIPTLS="true" CLUSTER=kind
on Mac.   It failed with

> STEP: creating a batch job
> INFO: Waiting on job to update status
> INFO: Timeout waiting for job to complete
> INFO: Pod logs for unpack job pod "deploy-bundle-image-srqsf-66j9z":
> standard_init_linux.go:228: exec user process caused: exec format error
> 

I seems to run the mac executable in the linux container.  I built linux executables and run ’make e2e`.   It worked successfully.

**Comment by exdx** [comment]
I was able to reproduce. Thank you for putting up a PR.
