### ISSUE TITLE
index catalog not working on ppc64le and s390x

### ISSUE THREAD

**Issue by sxd** [operator-framework/operator-registry#792]
Currently we build the index catalog with the following Dockerfile:
```
FROM quay.io/operator-framework/opm:latest
LABEL operators.operatorframework.io.index.database.v1=/database/index.db
ADD database/index.db /database/index.db
EXPOSE 50051
ENTRYPOINT ["/bin/opm"]
CMD ["registry", "serve", "--database", "/database/index.db"]
```
This actually work perfectly on x86 but when going into ppc64le or s390x we hit the following issue:
```
WARN[0000] DEPRECATION NOTICE:
Sqlite-based catalogs and their related subcommands are deprecated. Support for
them will be removed in a future release. Please migrate your catalog workflows
to the new file-based catalog format.
time="2021-09-28T16:53:34Z" level=warning msg="error setting soft heap limit for sqlite" database=database/index.db error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub" port=50051
time="2021-09-28T16:53:34Z" level=warning msg="couldn't migrate db" database=database/index.db error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub" port=50051
time="2021-09-28T16:53:34Z" level=warning msg="couldn't list tables in db" database=database/index.db error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub" port=50051
time="2021-09-28T16:53:34Z" level=warning msg="no tables found in db" database=database/index.db port=50051
time="2021-09-28T16:53:34Z" level=fatal msg="failed to listen: listen tcp :50051: bind: address already in use" database=database/index.db port=50051
```
We tried looking into the image bug we were not able to find anything that we can modify.

We actually found that in the Makefile [here](https://github.com/operator-framework/operator-registry/blob/master/Makefile#L50) is enabled:
```
	GOOS=darwin CC=o64-clang CXX=o64-clang++ CGO_ENABLED=1 $(GO) build $(opm_version_flags) $(TAGS) -o "bin/darwin-amd64-opm" --ldflags "-extld=o64-clang" ./cmd/opm
```
Looking into the GoReleaser and the build process we have the multi-arch enabled, but also [GoReleaser has an issue](https://goreleaser.com/limitations/cgo/) enabling CGO in the build process.

So the question here is: How we can proceed to create a proper multi-arch index catalog?

**Comment by joelanford** [comment]
Thanks for the issue report! This is definitely something that we expect to work, so it seems we have a bug in the GoReleaser build process. 

That GoReleaser issue seems to be specific to the GoReleaser docker image (?), which is not used by opm's build configuration.

It looks like we may just need to set `CGO_ENABLED=1` in the goreleaser build configs for each platform-specific binary (e.g. [here](https://github.com/operator-framework/operator-registry/blob/c7f37721942eb2cce7530cde6cd19debff548fab/.goreleaser.yaml#L10))

**Comment by sxd** [comment]
@joelanford yeah probably adding the flag there should do the work but we're creating the test first to confirm if it works!

**Comment by sxd** [comment]
@joelanford so this works for building process:

```diff
diff --git a/.goreleaser.yaml b/.goreleaser.yaml
index 49244359..af03d4e7 100644
--- a/.goreleaser.yaml
+++ b/.goreleaser.yaml
@@ -8,6 +8,7 @@ builds:
       - amd64
     env:
       - CC=gcc
+      - CGO_ENABLED=1
     mod_timestamp: "{{ .CommitTimestamp }}"
     flags: &build-flags
       - -tags=json1
@@ -30,6 +31,7 @@ builds:
       - arm64
     env:
       - CC=aarch64-linux-gnu-gcc
+      - CGO_ENABLED=1
     mod_timestamp: "{{ .CommitTimestamp }}"
     flags: *build-flags
     asmflags: *build-asmflags
@@ -44,6 +46,7 @@ builds:
       - ppc64le
     env:
       - CC=powerpc64le-linux-gnu-gcc
+      - CGO_ENABLED=1
     mod_timestamp: "{{ .CommitTimestamp }}"
     flags: *build-flags
     asmflags: *build-asmflags
@@ -58,6 +61,7 @@ builds:
       - s390x
     env:
       - CC=s390x-linux-gnu-gcc
+      - CGO_ENABLED=1
     mod_timestamp: "{{ .CommitTimestamp }}"
     flags: *build-flags
     asmflags: *build-asmflags
@@ -72,6 +76,7 @@ builds:
       - amd64
     env:
       - CC=x86_64-w64-mingw32-gcc-posix
+      - CGO_ENABLED=1
     mod_timestamp: "{{ .CommitTimestamp }}"
     flags: *build-flags
     asmflags: *build-asmflags
```
We will test this base image if you want we can create a PR for this

**Comment by joelanford** [comment]
That'd be great! Thanks!

**Comment by mnencia** [comment]
I've tested the fix on my machine and it works. I've opened the PR #739

**Comment by sxd** [comment]
The PR is #793 there was a typo in the above comment :)

**Comment by sxd** [comment]
@joelanford can you re-run this action? https://github.com/operator-framework/operator-registry/actions/runs/1286855052 it failed pushing images to quay.io :/
