### ISSUE TITLE
CI failed due to 500 internal error

### ISSUE THREAD

**Issue by sxd** [operator-framework/operator-registry#794]
We have reported an issue that was closed by the PR #793  but when it was merged into `master` branch the build process didn't finish so we cannot test this branch on the s390x and ppc64le architectures for now, is it possible to re-run this process: https://github.com/operator-framework/operator-registry/actions/runs/1286855052 ?

Thanks in advance!

**Comment by joelanford** [comment]
Looks like all the images and manifest list for `master` are pushed correctly this time. Thanks for letting us know!
