### ISSUE TITLE
readiness probe failing on multiarch

### ISSUE THREAD

**Issue by sxd** [operator-framework/operator-registry#795]
Due that the project [grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe) build the container only for `linux/amd64` the readiness probe fail when running on multi-arch and pod goes into `CrashLoopBackOff`.

Working on a fix now.

**Comment by sxd** [comment]
Pull request created #796

**Comment by sxd** [comment]
@joelanford can you look into this patch?

**Comment by joelanford** [comment]
It might be even simpler: Looks like we should have used $TARGETPLATFORM, not $BUILDPLATFORM, in the FROM grpc image line.

**Comment by sxd** [comment]
@joelanford the thin is that grpc image isn't multi-arch we're working with @mnencia on creating a patch for that, but not sure if it will be fast =(

**Comment by sxd** [comment]
The related PR on the grpc-health-probe is here:   https://github.com/grpc-ecosystem/grpc-health-probe/pull/86
