### ISSUE TITLE
"opm alpha diff" still have the omitted channels

### ISSUE THREAD

**Issue by Xia-Zhao-rh** [operator-framework/operator-registry#816]
please check bellow output.
[root@preserve-olm-agent-test JIRA-2196]# opm version
Version: version.Version{OpmVersion:"v1.19.1", GitCommit:"c426f78b", BuildDate:"2021-10-19T06:41:37Z", GoOs:"linux", GoArch:"amd64"}

`[root@preserve-olm-agent-test JIRA-2196]# opm alpha list bundles quay.io/xzhao/catalog-test:2196
PACKAGE         CHANNEL      BUNDLE                           REPLACES                         SKIPS  SKIP RANGE  IMAGE
ditto-operator  alpha        ditto-operator.v0.1.0                                                                quay.io/xzhao/ditto-operator:0.1.0-2196
ditto-operator  alpha        ditto-operator.v0.1.1            ditto-operator.v0.1.0                               quay.io/xzhao/ditto-operator:0.1.1-2196
ditto-operator  beta         ditto-operator.v0.1.1                                                                quay.io/xzhao/ditto-operator:0.1.1-2196
ditto-operator  beta         ditto-operator.v0.2.0            ditto-operator.v0.1.1                               quay.io/xzhao/ditto-operator:0.2.0-2196
etcd            clusterwide  etcdoperator.v0.9.2-clusterwide                                                      quay.io/xzhao/etcd-operator:0.9.2-clusterwide-2196
etcd            clusterwide  etcdoperator.v0.9.4-clusterwide  etcdoperator.v0.9.2-clusterwide                     quay.io/xzhao/etcd-operator:0.9.4-clusterwide-2196
etcd            single       etcdoperator.v0.9.2                                                                  quay.io/xzhao/etcd-operator:0.9.2-2196
etcd            single-2     etcdoperator.v0.9.4                                                                  quay.io/xzhao/etcd-operator:0.9.4-2196

[root@preserve-olm-agent-test JIRA-2196]# cat include.yaml1
packages: 
  - name: ditto-operator
    channels:
    - name: alpha
  - name: etcd
    channels: 
    - name: single-2

[root@preserve-olm-agent-test JIRA-2196]# opm alpha diff quay.io/xzhao/catalog-test:2196 -i include.yaml1 -o json | jq '{name, schema}|select(.schema=="olm.bundle")'| jq '{name}'
{
  "name": "ditto-operator.v0.1.0"
}
{
  "name": "ditto-operator.v0.1.1"
}
{
  "name": "ditto-operator.v0.2.0"
}
{
  "name": "etcdoperator.v0.9.2"
}
{
  "name": "etcdoperator.v0.9.4"
}
{
  "name": "etcdoperator.v0.9.4-clusterwide"
}

[root@preserve-olm-agent-test JIRA-2196]# opm alpha diff quay.io/xzhao/catalog-test:2196 -i include.yaml1 -o json | jq 'select(.schema=="olm.channel")'
{
  "schema": "olm.channel",
  "name": "alpha",
  "package": "ditto-operator",
  "entries": [
    {
      "name": "ditto-operator.v0.1.0"
    },
    {
      "name": "ditto-operator.v0.1.1",
      "replaces": "ditto-operator.v0.1.0"
    }
  ]
}
{
  "schema": "olm.channel",
  "name": "beta",
  "package": "ditto-operator",
  "entries": [
    {
      "name": "ditto-operator.v0.2.0",
      "replaces": "ditto-operator.v0.1.1"
    }
  ]
}
{
  "schema": "olm.channel",
  "name": "clusterwide",
  "package": "etcd",
  "entries": [
    {
      "name": "etcdoperator.v0.9.4-clusterwide",
      "replaces": "etcdoperator.v0.9.2-clusterwide"
    }
  ]
}
{
  "schema": "olm.channel",
  "name": "single",
  "package": "etcd",
  "entries": [
    {
      "name": "etcdoperator.v0.9.2"
    }
  ]
}
{
  "schema": "olm.channel",
  "name": "single-2",
  "package": "etcd",
  "entries": [
    {
      "name": "etcdoperator.v0.9.4"
    }
  ]
}`

**Comment by estroz** [comment]
This is not a bug. The heads-only diff is created, then all packages, channels, and versions you specify in the include file are added on top of that diff. Omitted channels will only not appear if there are no new versions in that channel when running diff in latest mode. One of the CLi examples explains this behavior:

```console
# Create a heads-only catalog, but include all of package "foo", package "bar" channel "stable",
# and package "baz" channel "alpha" version "0.2.0-alpha.0" (and its upgrade graph) in the diff.
cat <<EOF > include.yaml
packages:
- name: foo
- name: bar
  channels:
  - name: stable
- name: baz
  channels:
  - name: alpha
    versions:
    - 0.2.0-alpha.0
EOF
opm alpha diff registry.org/my-catalog:def456 -i include.yaml -o yaml > my-catalog-index/index.yaml
```

However this behavior will no longer be the default after #819 merges because the current behavior is confusing.

/close
