### ISSUE TITLE
Opm render output could be a package directory structure.

### ISSUE THREAD

**Issue by J0zi** [operator-framework/operator-registry#871]
Hi team.

Currently, `opm render some_index`  produces a single file. Our goal is to have package based directory structure with files per package at least. Even better is to have something like this:
```
configs
├── aqua
│   ├── 0.0.1.yaml
│   └── 0.0.2.yaml
└── cocroachdb
    ├── 0.0.1.yaml
    └── 0.0.2.yaml
```
Could you please implement a feature, that output will not a be a single file but directories per package and respected yaml files inside?

Thank you

**Comment by joelanford** [comment]
This feature already exists as `opm migrate`. Does that command work for your use case?

**Comment by J0zi** [comment]
It provides output like this:
```
configs
├── aqua
│   └── catalog.yaml
└── cocroachdb
    └── catalog.yaml
```
For now, it is great. However we will see if it is sufficient for our case. Thank you:)
