### ISSUE TITLE
Catalog built with the new builder image fail to deploy the bundles.

### ISSUE THREAD

**Issue by rgomez-casa** [operator-framework/operator-registry#889]
We are using an old version of opm due to compatibility issues:
opm version:
Version: version.Version{OpmVersion:"1.12.3", GitCommit:"", BuildDate:"2020-05-28T18:42:07Z", GoOs:"linux", GoArch:"amd64"}

The catalogs built using image released last week:
quay.io/operator-framework/upstream-opm-builder@sha256:add00173bc697dd0f69d038cb28c847cc5bfa019128b3a711eec3440cba6d324

Are failing to deploy with the following error on the catalog-operator:

time="2021-12-14T15:11:05Z" level=warning msg="failed to construct operator from bundle, continuing: couldn't parse bundle path, missing provided and required apis" catalog="{casa-redis-sentinel openshift-marketplace}"

Using an older image as base for the catalog does not cause this problem:

quay.io/operator-framework/upstream-opm-builder@sha256:49a3dc17e128c1fa687b9237780d95d522359b304aa8a94b9eee0ee66e792b1b

**Comment by dinhxuanvu** [comment]
Given your `opm` binary is very gold (circa 2020), I would recommend you to use a newer `opm`. Or you still insist on using older `opm` binary, then you will need to find an older builder image to suit that binary. There are schema DB changes over time and there are DB migrations accommodating these schema changes in the builder images. So older binary may not work with newer builder images.

**Comment by grokspawn** [comment]
closed this as idle too long (7 months)
