### ISSUE TITLE
[Feature Request] Support for Podman default auth file

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-registry#906]
Description of problem:
"opm render" and "opm alpha diff" does not read podman default auth file

Steps to Reproduce:
1.add auth to podman default auth file ${XDG_RUNTIME_DIR}/containers/auth.json

2. test auth 
[cloud-user@preserve-olm-agent-test ~]$ podman pull quay.io/xzhao/etcd-operator:0.9.4-2196
Trying to pull quay.io/xzhao/etcd-operator:0.9.4-2196...
Getting image source signatures
Copying blob 324b6f8a769d done  
Copying blob f51c45fff73d done  
Copying config f3523f6de0 done  
Writing manifest to image destination
Storing signatures
f3523f6de01e782b17c8fc3cf523c3b05c4d0063cc9e73781218eb3c5c1e3e09

3. run opm render opm alpha diff
[cloud-user@preserve-olm-agent-test ~]$ opm render quay.io/xzhao/etcd-operator:0.9.4-2196
2022/01/14 09:53:41 render reference "quay.io/xzhao/etcd-operator:0.9.4-2196": error resolving name : unexpected status code [manifests 0.9.4-2196]: 401 UNAUTHORIZED

[cloud-user@preserve-olm-agent-test ~]$ opm alpha diff quay.io/xzhao/etcd-operator:0.9.4-2196
FATA[0000] error generating diff: error rendering new refs: render reference "quay.io/xzhao/etcd-operator:0.9.4-2196": error resolving name : unexpected status code [manifests 0.9.4-2196]: 401 UNAUTHORIZED 

Actual results:
"opm render" and "opm alpha diff" does not read podman default auth file

Expected results:
"opm render" and "opm alpha diff" read podman default auth file to get image.

Additional info:
it is better to add one paramter `--authfile` to use specific authfile

**Comment by joelanford** [comment]
I believe this has already been implemented by #897

**Comment by Xia-Zhao-rh** [comment]
Hi, @joelanford 
Thanks a lot for your reply.
I checked the #897, it set the podman default auth file to be ${XDG_RUNTIME_DIR}/containers/auth.json

Is there any plan to support bellow situations?
1) the default path of the authentication file is overridden by setting the REGISTRY_AUTH_FILE environment variable. export REGISTRY_AUTH_FILE=path
2) add one option --authfile to use specific authfile like podman usage
3) when using root account, if XDG_RUNTIME_DIR is not in environment, the default authentication file  will 
 be /run/containers/0/auth.json

[root@preserve-olm-agent-test ~]# whoami
root
[root@preserve-olm-agent-test ~]# echo $REGISTRY_AUTH_FILE

[root@preserve-olm-agent-test ~]# podman login quay.io --verbose
Username: xxxxx
Password: 
Used:  /run/containers/0/auth.json
Login Succeeded!

**Comment by joelanford** [comment]
@Xia-Zhao-rh AFAIK, we believed #897 was sufficient to close out the original feature request, so there's no further work planned. That doesn't necessarily mean we can't make improvements.

One consideration though: since the code in question isn't actually using podman, I'm not sure it makes sense for `opm`'s in-process containerdregistry implementation to attempt to behave exactly like podman does.

Perhaps we could look into whether podman has a helper function for loading auth configuration, and we could re-use that?
