### ISSUE TITLE
FBC - opm index prune

### ISSUE THREAD

**Issue by betoredhat** [operator-framework/operator-registry#920]
Hello team, 

According to https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/512  
"opm index prune may be updated in the future to support both formats (SQLite/fbc)", is there a bug/issue already open to tracking when this will be available? 

Thanks

**Comment by grokspawn** [comment]
Hi @betoredhat , we have a [PR](https://github.com/operator-framework/operator-registry/pull/965) which clarifies that we will not be enhancing `opm index prune` to handle FBC catalogs.
