### ISSUE TITLE
 Release OPM with skip-tls-verify and use-http flag support in opm render

### ISSUE THREAD

**Issue by ryanemerson** [operator-framework/operator-registry#925]
https://github.com/operator-framework/operator-registry/pull/909 adds support for the `skip-tls-verify` and `use-http` flag to `opm render`.

# Feature Motivation
The [Infinispan operator](https://github.com/infinispan/infinispan-operator) testsuite creates a custom `CatalogSource` based upon operathub.io's CatalogSource in order to test that an update from the latest released version to the current dev branch works as expected.

Operatorhub has started to migrate it's catalogue's from the old SQLite format to the FBC format, which means we need to update our workflow to utilise the `opm render` command instead of `opm index add` https://github.com/infinispan/infinispan-operator/pull/1375/files. As part of this workflow, we push the created catalog image to a local docker registry to avoid pushes to quay.io etc.

When using this local registry, it's not possible to execute `opm render <local-registry>/<catalog-image>` as the registry is only configured for `http`.

Similarly, if the registry is updated to use `https`, it's not possible to connect to a local `https` registry as the machine's local `containerd` configuration is ignored and it's not possible to provide the registry CA certificates to `opm render`.

https://github.com/operator-framework/operator-registry/pull/909 allows us to continue using either the local `http` or `https` registry by setting the flags as required.

# Release Required
Currently we're working around the `opm` limitations by using a temporary image tag quay.io/operatorhubio/catalog:tmp_latest_sql that still uses the old SQLite format. However, this tag will be removed in April. Therefore, we require a `opm` release before April so that we can adopt the `opm render` approach before the tag's removal.

Based upon comments and +1 on my original PR, I think there are a few teams who are in a similar position.

**Comment by phantomjinx** [comment]
To chime with @ryanemerson, the camel-k project is in a similar position as we conduct e2e tests that exercise the upgrade capability of our operator, using a local http-only docker registry. Up until this point, we've had to let our upgrade tests fails due to a working `opm` with http capability.

Now that #909 has been merged we can install from the commit hash but an `opm` release would be preferable.

**Comment by exdx** [comment]
This looks like a very handy feature and we will include it in the next operator-registry release. I will try to cut a release soon to get the flag support out there.

**Comment by exdx** [comment]
Just cut a new registry release with this commit https://github.com/operator-framework/operator-registry/releases/tag/v1.21.0. Closing this issue.

**Comment by ryanemerson** [comment]
Thanks @exdx
