### ISSUE TITLE
Opm render/migrate/export are pruning the orphan bundles

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-registry#961]
### Description
Opm render/migrate/export are pruning the orphan bundles. 

Example scenario: The following example scenario has two bundles added to the SQLIndex and without any configuration for the upgraded graph. By running the commands we are only able to check the latest version added.

### Steps to reproduce

1. Check the SQLIndex (registry.redhat.io/redhat/redhat-marketplace-index) and the package k10-kasten-operator-rhmp:

<img width="841" alt="Screenshot 2022-05-19 at 16 35 35" src="https://user-images.githubusercontent.com/7708031/169695780-722d7c4c-0cbb-4186-85f3-58f947b148d9.png">

<img width="700" alt="Screenshot 2022-05-19 at 16 36 20" src="https://user-images.githubusercontent.com/7708031/169695776-f84a5012-86d3-49bc-9c6c-53cae1ba112e.png">

2. Then, by running the following commands we can check that only the bundle v4.5.14 is migrated: 

```sh
opm index export --index="registry.redhat.io/redhat/redhat-marketplace-index:v4.9" --skip-tls --package=k10-kasten-operator-rhmp
cd downloaded/
cd k10-kasten-operator-rhmp/
$ ls
4.5.14		package.yaml
```

OR

```sh
mkdir marketplace
opm migrate registry.redhat.io/redhat/redhat-marketplace-index:v4.9 marketplace/
```

### What problems it might cause:

By not migrating and showing the orphan bundles index admins and/or Operator authors are unable to for example change the data and add the missing replaces

**Comment by camilamacedo86** [comment]
c/c @joelanford

**Comment by joelanford** [comment]
I'm fairly sure that if we rendered or migrated the database with the orphaned bundles, it would result in an invalid FBC.

I'm not super familiar with the motivation behind keeping these orphaned bundles around in the sqlite database. Do we do that on purpose? If so, do we have that motivation written down anywhere?

Render and migrate work by calling the equivalent of the GRPC`ListBundles` function to ensure that the resulting FBC is exactly the same as the original sqlite db from the perspective of OLM. So if those bundles are not in the `ListBundles` output, they won't be in the FBC.

**Comment by camilamacedo86** [comment]
Hi @joelanford 

> I'm fairly sure that if we rendered or migrated the database with the orphaned bundles, it would result in an invalid FBC.

Yes, I thought on that as well. However, what seems to be the cons: the authors lost the bundles and would not be able to indeed fix the previous scenarios or check that they exist.

However, from FBC (from the moment that authors opt-in to use it) we can ensure that this scenario will no longer happen since FBC is validating the upgrade path and will not allow orphan bundles to be defined. I mean, from FBC we do not allow orphan bundles to be defined for so long and the problem is fixed.  Am I right?

Then, I think the question is: should we allow authors to check these scenarios after the migration so that they are able to fix what was published previously? If not, then I think we can close this one since it is working as expected. WDYT?

**Comment by camilamacedo86** [comment]
On top of that, I think we need to clarify the prune behaviour for the commands in the docs, and maybe we could add a note in its helpers as well.

**Comment by camilamacedo86** [comment]
We could confirm that the export command will return the data as it is resolved by OLM. So, orphan bundles that will not be returned are not exported. (i.e. bundles without valid paths like missing replaces/skips/skipRange )

Therefore since the behaviours and commands are part of the legacy format to store the content SQLIndex seems like we can defer any further action here. Therefore, I am closing this issue.
