### ISSUE TITLE
opm version not working in the v1.18.0 binary showing a sha instead

### ISSUE THREAD

**Issue by austincunningham** [operator-framework/operator-registry#981]
on 1.17 version is returned 
```bash
opm version
Version: version.Version{OpmVersion:"v1.17.0", GitCommit:"ebeac77", BuildDate:"2021-04-13T18:40:36Z", GoOs:"linux", GoArch:"amd64"}
```

downloaded the binary from https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest-4.9/opm-linux.tar.gz
updated my binary to v1.18.0 version command showing a sha
```bash
opm version                      
Version: version.Version{OpmVersion:"b1110c6d1", GitCommit:"b1110c6d14e549babb2bd7d6dea4ff6402c617a2", BuildDate:"2022-06-09T06:33:39Z", GoOs:"linux", GoArch:"amd64"}
```

**Comment by grokspawn** [comment]
Hi @austincunningham.  OCP versions of `opm` are not synched with the upstream tags since they are separate repositories, so we would expect that binaries distributed with OCP would almost always display a SHA for OpmVersion.
